//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebClient.EmployeeService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeService.EmployeeServiceSoap")]
    public interface EmployeeServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetEmployee(int empid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetEmployeeAsync(int empid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEmployees", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveEmployee(MyWebClient.EmployeeService.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SaveEmployeeAsync(MyWebClient.EmployeeService.Employee emp);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Employee : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int empIdField;
        
        private string empNameField;
        
        private decimal salaryField;
        
        private string addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int EmpId {
            get {
                return this.empIdField;
            }
            set {
                this.empIdField = value;
                this.RaisePropertyChanged("EmpId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EmpName {
            get {
                return this.empNameField;
            }
            set {
                this.empNameField = value;
                this.RaisePropertyChanged("EmpName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Salary {
            get {
                return this.salaryField;
            }
            set {
                this.salaryField = value;
                this.RaisePropertyChanged("Salary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeServiceSoapChannel : MyWebClient.EmployeeService.EmployeeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceSoapClient : System.ServiceModel.ClientBase<MyWebClient.EmployeeService.EmployeeServiceSoap>, MyWebClient.EmployeeService.EmployeeServiceSoap {
        
        public EmployeeServiceSoapClient() {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetEmployee(int empid) {
            return base.Channel.GetEmployee(empid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetEmployeeAsync(int empid) {
            return base.Channel.GetEmployeeAsync(empid);
        }
        
        public System.Data.DataTable GetAllEmployees() {
            return base.Channel.GetAllEmployees();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllEmployeesAsync() {
            return base.Channel.GetAllEmployeesAsync();
        }
        
        public string SaveEmployee(MyWebClient.EmployeeService.Employee emp) {
            return base.Channel.SaveEmployee(emp);
        }
        
        public System.Threading.Tasks.Task<string> SaveEmployeeAsync(MyWebClient.EmployeeService.Employee emp) {
            return base.Channel.SaveEmployeeAsync(emp);
        }
    }
}
